### ISSUE TITLE
Rounding of width

### ISSUE THREAD

**Issue by joto** [Nathanael-L/osmi-water#8]
The width of a waterway shows up wrong. In this example the original `width=0.7` appears as `0.699999988079071`:
http://tools.geofabrik.de/osmi/?view=water&lon=13.81737&lat=51.07410&zoom=16

**Comment by woodpeck** [comment]
This had actually been fixed in d882cca9dc93c6b28c6683e890f8a40bb49c54aa which has been deployed today, will take another day for the new results to propagate to the web site.
